apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name}}
spec:
  replicas: {{ .Values.replicasSet}}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: {{ .Values.containers.name}}
          image: nginx
          ports:
            - containerPort: 80

